### ISSUE TITLE
propose_to_be_provider extrinsic should reject bad names

### ISSUE THREAD

**Issue by shannonwells** [frequency-chain/frequency#1654]
# Problem 
I was able to add a motion via `propose_to_be_provider` with an invalid provider name (`somethingverylongthatIknowwill fail` to be specific), because it's just a passthrough.  The extrinsic would fail on execution, however, it's undesirable to have people create trash proposals for a number of reasons.

## expected:
the transaction to fail

## actual
the transaction succeeded and a Council motion was created.  

# Solution
Apply existing restrictions to `propose_to_be_provider` which would fail if the same provider name were submitted via `create_provider`

**Comment by wilwade** [comment]
Re: Character validations. I don't think so? The provider name is not human validated. On Rococo for example we have many providers with the same name due to test runs.

It is more for self discovery and easy development than anything else. Assuming you know what you named your provider (and no one else uses that name), you can find yourself.

I think there is a future where we have some provider registry data here that could be validated. One example would be a domain name. The domain data is unvalidated on chain, but a DNS txt record can be used to validate as needed.

**Comment by shannonwells** [comment]
Sounds good.  Existing restrictions should stay the same, and be applied on the proposal. Updated the description.
