### ISSUE TITLE
Potential Handle issues

### ISSUE THREAD

**Issue by wilwade** [frequency-chain/frequency#2213]
- [ ] Some validating handles are using incorrect length (Check with Frqcy Access)
- [x] Capacity Batching should be atomic, but might not be (or is not rolling back state?)
- [ ] projectlibertylabs/gateway#676
- [ ] Can SIWF return just a handle without a create MSA (currently no, but likely low priority for the time being.)

**Comment by mattheworris** [comment]
Update: Not able to reproduce any issues with Frequency not correctly reverting pay with capacity batch calls. 

- Setup with gateway/tools/example.mjs, running `account-service` locally, and used SIWF v2 and a handle that is greater than 20 characters. The claimHandle transaction fails which should cause the create sponsored account to fail as well. 
- Follow on attempts to create a new user with the same email address do not get stuck (as was originally observed-it was because an MSA was created), which indicates that the transaction to create an MSA was also reverted when the claim handle failed.
- Verified on-chain that no MSA was created from the reverted transactions.

**Comment by wilwade** [comment]
Closing as not reproducible.
